config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"

  mount Rswag::Ui::Engine => "/api-docs"

  devise_for :users

  resources :csv_uploads

  namespace :api do
    namespace :v1 do
      resources :planning_applications, only: %i[index create]
    end
  end

  get :healthcheck, to: proc { [200, {}, %w[OK]] }
end

app/models/csv_upload.rb
# frozen_string_literal: true

class CsvUpload < ApplicationRecord
  has_many_attached :csv_files
  has_many :csv_processing_messages, dependent: :destroy

  def filtered_csv_processing_messages
    success_message = csv_processing_messages
                      .where(message_type: 0)
                      .order(created_at: :desc)
                      .first

    error_messages = csv_processing_messages
                     .where(message_type: 1)
                     .order(created_at: :desc)

    if success_message.present?
      error_messages.or(
        CsvProcessingMessage.where(id: success_message.id)
      )
    else
      error_messages
    end
  end
end

app/controllers/csv_uploads_controller.rb
# frozen_string_literal: true

class CsvUploadsController < ApplicationController
  before_action :set_csv_upload, only: %i[show edit update destroy]

  # GET /csv_uploads or /csv_uploads.json
  def index
    @csv_uploads = CsvUpload.all
  end

  # GET /csv_uploads/1 or /csv_uploads/1.json
  def show; end

  # GET /csv_uploads/new
  def new
    @csv_upload = CsvUpload.new
  end

  # GET /csv_uploads/1/edit
  def edit; end

  # POST /csv_uploads or /csv_uploads.json
  def create
    @csv_upload = CsvUpload.new(csv_upload_params)

    respond_to do |format|
      if @csv_upload.save
        format.html do
          redirect_to csv_upload_url(@csv_upload), notice: I18n.t("upload_successfully_created_notice")
        end
        format.json { render :show, status: :created, location: @csv_upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @csv_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_uploads/1 or /csv_uploads/1.json
  def update
    respond_to do |format|
      if @csv_upload.update(csv_upload_params)
        format.html { redirect_to csv_upload_url(@csv_upload), notice: I18n.t("upload_successfully_updated_notice") }
        format.json { render :show, status: :ok, location: @csv_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @csv_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_uploads/1 or /csv_uploads/1.json
  def destroy
    @csv_upload.destroy

    respond_to do |format|
      format.html { redirect_to csv_uploads_url, notice: I18n.t("upload_successfully_destroyed_notice") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_csv_upload
    @csv_upload = CsvUpload.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def csv_upload_params
    params.require(:csv_upload).permit(:title, csv_files: [])
  end
end

app/helpers/csv_uploads_helper.rb
# frozen_string_literal: true

module CsvUploadsHelper
end

app/views/csv_uploads/_csv_upload.html.erb
<div id="<%= dom_id csv_upload %>">
  <h2 class="govuk-heading-m"><%= csv_upload.title %></h2>
  <h3 class="govuk-heading-s">Progress</h3>
  <ul class="govuk-list govuk-list--bullet">
    <li>Starting import job...</li>
    <% csv_upload.filtered_csv_processing_messages.each do |msg| %>
    <li data-created-at="<%= msg.created_at %>" data-message-id="<%= msg.id %>"><%= msg.body %></li>
    <% end %>
  </ul>
  <h3 class="govuk-heading-s">Attached files</h3>
  <ul class="govuk-list govuk-list--bullet">
    <% csv_upload.csv_files.each do |csv| %>
       <li><%= link_to csv.filename, csv %></li>
    <% end %>
  </ul>
</div>

app/views/csv_uploads/_form.html.erb
<%= form_with(model: csv_upload, data: { controller: "direct-file-uploader" }) do |form| %>
  <% if csv_upload.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(csv_upload.errors.count, "error") %> prohibited this csv_upload from being saved:</h2>

      <ul>
        <% csv_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class=govuk-form-group>
    <%= form.label :title, class: 'govuk-label' %>
    <%= form.text_field :title, class: 'govuk-file-upload' %>
  </div>

  <div class=govuk-form-group>
    <%= form.label :csv_files, 'Upload CSV files', class: 'govuk-label' %>
    <%= form.file_field :csv_files, multiple: true, accept: ".csv", direct_upload: true, class: 'govuk-file-upload', data: { action: 'change->direct-file-uploader#handleFileSelect' } %>
    <template class="directupload-progress">
    <p class="govuk-body"><strong class="govuk-tag">
      {{status}} <progress style="border: white 1px solid;" min="0" max="100" value="{{progress}}">{{progress}}%</progress>
    </strong> <span class="directupload-progress-filename"></span></p>
    </template>
  </div>

  <details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary">
      <span class="govuk-details__summary-text">
        CSV formats
      </span>
    </summary>
    <div class="govuk-details__text">
      CSV files must be of the following format:

      <table class="govuk-table">
        <caption class="govuk-table__caption govuk-table__caption--m">CSV formats</caption>
        <thead class="govuk-table__head">
          <tr class="govuk-table__row">
             <% ["reference","application_type_code","application_type","area","description","received_at","assessor","reviewer","decision","decision_issued_at","validated_at","uprn_","code","type","FULL","map_east","map_north","ward_code","ward_name","Neighbour_Consult_Expiry","Standard_Consult_Expiry","Overall_Expiry","Target_Determination_Date","Extension_of_Time_Date","PPA_DATE","Actual_Committee_Date","Permission_Expiry_Date","Appeal_Status","Date_Appeal_Lodged","Date_Appeal_Determined","DM_STATUS","DM_Deciesion","Development_Type","Application_Type","DM_Decision_Code"].each do |heading| %>
              <th scope="col" class="govuk-table__header"><%= heading %></th>
             <% end %>
          </tr>
        </thead>
        <tbody class="govuk-table__body">
          <tr class="govuk-table__row">
          <% ["reference","application_type_code","application_type","area","description","received_at","assessor","reviewer","decision","decision_issued_at","validated_at","uprn_","code","type","FULL","map_east","map_north","ward_code","ward_name","Neighbour_Consult_Expiry","Standard_Consult_Expiry","Overall_Expiry","Target_Determination_Date","Extension_of_Time_Date","PPA_DATE","Actual_Committee_Date","Permission_Expiry_Date","Appeal_Status","Date_Appeal_Lodged","Date_Appeal_Determined","DM_STATUS","DM_Deciesion","Development_Type","Application_Type","DM_Decision_Code"].each do |heading| %>
              <th scope="" class="govuk-table__header"><%= heading %></th>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
</details>

  <div>
    <%= form.submit 'Upload', {class: 'govuk-button'} %>
  </div>
<% end %>

app/views/csv_uploads/edit.html.erb
<h1>Editing csv upload</h1>

<%= render "form", csv_upload: @csv_upload %>

<br>

<div>
  <%= link_to "Show this csv upload", @csv_upload %> |
  <%= link_to "CSV Uploads", csv_uploads_path, { class: 'govuk-back-link' } %>
</div>

app/views/csv_uploads/index.html.erb
<h1 class=govuk-heading-l>CSV Uploads</h1>

<div id="csv_uploads">
  <% if @csv_uploads.empty? %>
   <div class="govuk-inset-text">
    No CSV files have been uploaded.
   </div>
  <% end %>
  <% @csv_uploads.each do |csv_upload| %>
    <%= render csv_upload %>
    <p class=govuk-body>
      <%= link_to "Show this csv upload", csv_upload %>
    </p>
  <% end %>
</div>

<%= link_to "New CSV Upload", new_csv_upload_path, {class: "govuk-body"} %>

app/views/csv_uploads/new.html.erb
<h1 class="govuk-heading-l">New CSV Upload</h1>

<%= render "form", csv_upload: @csv_upload %>

<br>

<div>
  <%= link_to "CSV Uploads", csv_uploads_path, { class: 'govuk-back-link' } %>
</div>

app/views/csv_uploads/show.html.erb
<%= render @csv_upload %>

<div>
  <div class="govuk-button-group">
    <%= button_to "Destroy this csv upload", @csv_upload, { class: 'govuk-button govuk-button--warning', method: :delete } %>
  </div>
  <%= link_to "CSV Uploads", csv_uploads_path, { class: 'govuk-back-link' } %>
</div>